### ISSUE TITLE
No transmission data to Wunderground / Error in Arduino Function missing

### ISSUE THREAD

**Issue by golvellius** [docwelch/Weather-Station#1]
Hi ...

First of all i would like to thank you about your supperb work .. I have been checking your code and works ok .
I have found two possible errors i can not recover ...
1) In the code of BeagleBoneBlack . The info arrives  from the arduino , it is displayed in the console of cloud9 IDE ,   but **never execute sendDataToWunderground()**; .. I see all the info comming from the arduino , but never sends data to internet ... 

2) Also there is a problem in the code of the Arduino , Line ...
*_baromin = myPressure.readPressureinHg(LOCAL_ALT_METERS); *_ 
I tried to get some libraries from internet , included the ones in SPARKFUN but no luck , the function does not exist .. I have made new routine from example in SPARKFUN .. i will check ...

Maybe i make some mistake ... 

Thanks a lot ...

**Comment by docwelch** [comment]
For issue #1, the problem is likely a small typo in function sendDataToWunderground(). I had a lot of trouble with my system as well. Please go back and review that you have your username and password correct and no other mistakes in the function where it creates the http request. When I was setting up my station, I had to review that section several times before I finally got all the errors out of it. 

For issue 2, it looks like Sparkfun has changed the library since I downloaded it. You are correct, the function no longer exists. They have made a lot of changes to the library it looks like and this will require some re-writing of the code. It should not be too difficult if you look at the example sketches [Sparkfun MPL3115A2 Pressure Sensor Library.](https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library.) You can also look at [Sparkfun Wimp Weather Station Arduino Code](https://github.com/sparkfun/Wimp_Weather_Station/blob/master/Wimp_Weather_Station.ino) as it looks like Sparkfun updated this as well. Looks like you just need to set up the barometer in the void Setup() function, and then you call for pressure with just readPressure(). It returns the value in Pa so you will have to convert if you want a different unit. You will no longer need the LOCAL_ALT_METERS variable.

Glad this is useful to someone and I hope my response is helpful. Let me know if you cannot figure it out. I think I may have to take down my weather station and add the lightning sensor. I am sure I will change over to the new library and I will update the code then. However, it may be several weeks (or months) before I get to it, unfortunately. I will leave this issue open until I have time to fix the code.

**Comment by golvellius** [comment]
Hi  ...
I think i have my issue  with the code .. maybe hardware xbee issue ...

What  i see is that i get data from the xbee but maybe wrong data ..

On this function ...i modified to tell me things in the console ... 

xbeeAPI.on('frame_object',function(frame){
    console.log("XBEE");
    if (frame.type==C.FRAME_TYPE.RX_PACKET_16){
        console.log("XBEEIN");
        dataArray.length=0;
        weatherArray.length=0;
        var winddir=((frame.data[0]<<8)+frame.data[1]);
etc ....

I see in the console XBEE but not XBEE1 ... never execute this function ...

Can you tell me your xbee configuration .... ?

I think that this is the problem ...

**Comment by golvellius** [comment]
Hi ...

Now Working .. it's a problem with the ap mode of the xbeess ... 

Thanks for this great CODE ...

If you want i can send you the code in your source to readPressure in HG in the arduino code , i need to check if it is working correctly .... 

Thanks a lot ...

**Comment by golvellius** [comment]
Hi ..

I have been using it for 2 month , but i have problems maybe with my battery charger ..
Suddenly , battery get's empty an solar panel can not charge ... 

What are you using ? Solar Panel + BAttery charger + batteries ?

Thanks a lot ... Good job with this project ...
I am modifying the code to install lighting detector .... ; ) 

Please can you reply to me to this email golvelliuscs@hotmail.com ..

bye

**Comment by docwelch** [comment]
I used a 2.5W solar cell and the Sunny Buddy MPPT charger from Sparkfun with a 5000mAh single cell LiPo battery.I never had a problem, even with several days of limited to no sunshine. I think the 5000mAh battery is probably quite a bit bigger than you would have to use, but they are cheap from HobbyKing.
Good luck with it,Steven
 Confidentiality Statement - This electronic message transmission contains information that is confidential or privileged.  The information is intended to be for the use of the individual or entity named above. If you are not the  intended recipient, be aware that any disclosure, copying, distribution or use of the contents of this information is prohibited.  If you have received this electronic transmission in error, please notify us immediately.  Thank you.

```
  From: golvellius <notifications@github.com>
```

 To: docwelch/Weather-Station Weather-Station@noreply.github.com 
Cc: Steven Welch docwelch@yahoo.com; Comment comment@noreply.github.com
 Sent: Tuesday, June 7, 2016 5:47 AM
 Subject: Re: [docwelch/Weather-Station] No transmission data to Wunderground / Error in Arduino Function missing (#1)

Hi ..I have been using it for 2 month , but i have problems maybe with my battery charger ..
Suddenly , battery get's empty an solar panel can not charge ... What are you using ? Solar Panel + BAttery charger + batteries ?Thanks a lot ... Good job with this project ...
I am modifying the code to install lighting detector .... ; ) Please can you reply to me to this email golvelliuscs@hotmail.com ..bye —
